services:

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - APP_DB_CONNECTION_STRING=root:gromizk123@tcp(db:3306)/c_loyal?charset=utf8mb4&parseTime=True&loc=Local
      - APP_PORT=8080

  db:
    image: bitnami/mysql
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=c_loyal
      - MYSQL_ROOT_PASSWORD=gromizk123
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p123456", "-e", "show schemas"]
      interval: 20s

  adminer:
    image: adminer
    restart: unless-stopped
    ports: # host:container
      - 8081:8080
